### ISSUE TITLE
[求问]部署在vercel的时候vercel好像会自动压缩静态文件

### ISSUE THREAD

**Issue by JIeJaitt** [Lete114/Hexo-minify#8]
如题，既然都会自动压缩，还有本地压缩的必要嘛

**Comment by lete114** [comment]
这个不清楚

**Comment by JIeJaitt** [comment]
> 这个不清楚

https://vercel.com/docs/edge-network/compression

**Comment by lete114** [comment]
> https://vercel.com/docs/edge-network/compression

这是网络传输压缩，而本插件为文件压缩，它们并不冲突。
文件压缩+网络传输压缩，体积更小速度更快
